### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by omaratr** [ChenfuShi/HiChIP_peaks#10]
When I try running this, I get an error at the converting hic-pro to sparse matrix step. I've coped the log file below. Could you provide some guidance on this?

INFO - Welcome to HiChIP-Peaks!
INFO - Version: 0.1.1
INFO - 2020-03-12 16:23:35.325021
INFO - Input variables
INFO - HiC-Pro data folder: {directory}
INFO - Restriction fragment file: {directory}
INFO - Chromosome annotation file: {directory}
INFO - Temporary location: {directory}
INFO - FDR: 0.01 
INFO - Distance from diagonal included: 2 
INFO - Output directory: {directory}
INFO - Output name prefix: sample1 
INFO - Keep temporary files?: False 
INFO - Threads(minimum is 4): 4 
INFO - Sex chromosomes correction: False 
INFO - Store object containing sparse matrix: False 
INFO - Loading experiment information and read pairs
INFO - #######################################
INFO - Start reading experiment information (restriction fragments and chromosomes)
INFO - #######################################
INFO - Preparing HiC-Pro output for import
INFO - #######################################
INFO - Converting HiC-Pro to sparse matrix rappresentation of valid pairs at restriction site resolution
Traceback (most recent call last):
  File "/software/python/Python-3.6.1/bin/peak_call", line 10, in <module>
    sys.exit(main())
  File "/software/python/Python-3.6.1/lib/python3.6/site-packages/hichip_peaks/main.py", line 126, in main
    CSR_mat,frag_index,frag_prop,frag_amount,valid_chroms,chroms_offsets = interaction_to_sparse.HiCpro_to_sparse(hicpro_results,resfrag,sizes,temporary_loc,prefix,keeptemp=keeptemp)
  File "/software/python/Python-3.6.1/lib/python3.6/site-packages/hichip_peaks/interaction_to_sparse.py", line 73, in HiCpro_to_sparse
    coo_data, coo_row, coo_col = Update_coo_lists_site(current_file,coo_data, coo_row, coo_col,valid_chroms,frag_index)
  File "/software/python/Python-3.6.1/lib/python3.6/site-packages/hichip_peaks/interaction_to_sparse.py", line 195, in Update_coo_lists_site
    frag_1 = info[8]
IndexError: list index out of range

Many thanks

**Comment by ChenfuShi** [comment]
Hello,
Don't know why i didn't receive any notification about this post.
This issue is caused by having extra files in the hic-pro output directory.
Can you make sure there are no extra files with the string "allValidPairs" in the hic-pro directory?

e.g. an older version of hicpro left a stats file in that folder.

**Comment by omaratr** [comment]
Thanks for your reply. That fixed the problem!
