### ISSUE TITLE
Sparse matrix error: number of read pairs parsed is 0. 

### ISSUE THREAD

**Issue by hrstu** [ChenfuShi/HiChIP_peaks#14]
Hi,

While running hichip-peaks for the first time, this error came up on multiple data sets. Below is the log file and error messages. Thanks for any help! 

INFO - Welcome to HiChIP-Peaks!
INFO - Version: 0.1.2
INFO - 2020-07-20 17:01:53.048280
INFO - Input variables
INFO - HiC-Pro data folder: {directory}
INFO - Restriction fragment file: {directory}/Ensemble_GRCh37_mobi.bed 
INFO - Chromosome annotation file: None 
INFO - Temporary location: {directory}
INFO - FDR: 0.01 
INFO - Distance from diagonal included: 2 
INFO - Output directory: {directory}
INFO - Output name prefix: sample_name 
INFO - Keep temporary files?: False 
INFO - Threads(minimum is 4): 4 
INFO - Sex chromosomes correction: False 
INFO - Store object containing sparse matrix: False 
INFO - Loading experiment information and read pairs
INFO - #######################################
INFO - Start reading experiment information (restriction fragments and chromosomes)
INFO - #######################################
INFO - Preparing HiC-Pro output for import
INFO - #######################################
INFO - Converting HiC-Pro to sparse matrix rappresentation of valid pairs at restriction site resolution
INFO - #######################################
INFO - Sparse matrix of experiment generated
INFO - Number of read pairs parsed: 0.0
INFO - #######################################
INFO - Extracting pairs for ChIP peaks calling
INFO - Number of reads used in peak calling: 0.0
WARNING - WARNING: number of reads used for peak calling is very low. Consider doing more sequencing
Traceback (most recent call last):
  File "/.conda/envs/hichip-peaks/bin/peak_call", line 8, in <module>
    sys.exit(main())
  File "/.conda/envs/hichip-peaks/lib/python3.7/site-packages/hichip_peaks/main.py", line 130, in main
    smoothed_diagonal, refined_peaks ,quick_peaks, peak_p_vals , peaks_q_vals ,expected_background= sparse_to_peaks.sparse_to_peaks(CSR_mat,frag_index,frag_prop,frag_amount,valid_chroms,chroms_offsets,output_dir,prefix,off_diag,chromX,FDR=FDR,threads=threads,keeptemp=keeptemp)
  File "/.conda/envs/hichip-peaks/lib/python3.7/site-packages/hichip_peaks/sparse_to_peaks.py", line 53, in sparse_to_peaks
    smoothed_diagonal = numpy.rint(moving_integration(diagonal,((off_diag-1)*2)+1)).astype(int) #### changed to 3 smoothing factor, it is one less than the number of off sites
  File "/.conda/envs/hichip-peaks/lib/python3.7/site-packages/hichip_peaks/sparse_to_peaks.py", line 86, in moving_integration
    sma = numpy.convolve(values, weights, 'same')
  File "<__array_function__ internals>", line 6, in convolve
  File "/.conda/envs/hichip-peaks/lib/python3.7/site-packages/numpy/core/numeric.py", line 815, in convolve
    raise ValueError('v cannot be empty')
ValueError: v cannot be empty

**Comment by ChenfuShi** [comment]
Hi, sorry for the delay.
it seems that it's not parsing any reads (INFO - Number of read pairs parsed: 0.0).
assuming that {directory} was manually substituted can you paste a head of the allValidPairs file?

Best

**Comment by hrstu** [comment]
Hi, Thanks for the response! Here are the first couple lines of the allValidPairs file. I should note we are using an older version of HiC-Pro (2.10.0) in case that could be a contributing factor. 

NB501311:598:HNTGVBGXF:2:13104:3829:1990        1       53220   +       3       106891020       +       106     HIC_1_103       HIC_3_250313    36      39      
NB501311:598:HNTGVBGXF:2:13304:15717:8260       1       94012   -       1       6958325 -       130     HIC_1_211       HIC_1_15983     35      42      
NB501311:598:HNTGVBGXF:2:23201:19314:17028      1       115753  -       22      51024588        -       271     HIC_1_261       HIC_22_95760    32      42      
NB501311:598:HNTGVBGXF:2:13103:10465:6282       1       133197  +       20      34877167        -       133     HIC_1_296       HIC_20_81586    36      36      
NB501311:598:HNTGVBGXF:2:22308:18309:4210       1       229611  -       20      37101018        -       119     HIC_1_434       HIC_20_88049    39      23

**Comment by ChenfuShi** [comment]
it seems like your chromosomes don't have chr in them. The default nomenclature includes chr in the chromosome names. you can solve this problem if you provide an annotation file which have the same nomenclature as the files you are processing.
you can provide that in the --annotation parameter
 ```
 -a SIZES, --annotation SIZES
                        HiCpro chromosome annotation file, default uses human
                        chromosomes, excludes chrY
```
by the way, when you provide that annotation make sure it doesn't include all the extra contigs and only have 1 to 22 and be careful of sex chromosomes (the correction currently requires your nomenclature to be chrX and chrY)

Let me know if this works

Best

**Comment by hrstu** [comment]
Hi, 

Thank you so much! That solved it!
