### ISSUE TITLE
p-value math domain error

### ISSUE THREAD

**Issue by AlagurajVeluchamy** [ChenfuShi/HiChIP_peaks#20]
I am getting math domain error. Is that because the p value is close to zero ?. 

INFO - Welcome to HiChIP-Peaks!
INFO - Version: 0.1.2
INFO - 2021-11-10 10:50:35.624014
INFO - Input variables
INFO - HiC-Pro data folder: K562.pipeline_output/HiCPro_out/hic_results/data/fastq
INFO - Restriction fragment file: /hg19_MboI_resfrag.bed
INFO - Chromosome annotation file: /hg19.v2.size
INFO - Temporary location: /code
INFO - FDR: 0.01
INFO - Distance from diagonal included: 2
INFO - Output directory: /code
INFO - Output name prefix: fastq
INFO - Keep temporary files?: False
INFO - Threads(minimum is 4): 10
INFO - Sex chromosomes correction: False
INFO - Store object containing sparse matrix: False
INFO - Loading experiment information and read pairs
INFO - #######################################
INFO - Start reading experiment information (restriction fragments and chromosomes)
INFO - #######################################
INFO - Preparing HiC-Pro output for import
INFO - #######################################
INFO - Converting HiC-Pro to sparse matrix rappresentation of valid pairs at restriction site resolution
INFO - #######################################
INFO - Sparse matrix of experiment generated
INFO - Number of read pairs parsed: 197369472.0
INFO - #######################################
INFO - Extracting pairs for ChIP peaks calling
INFO - Number of reads used in peak calling: 56181909.0
INFO - #######################################
INFO - Identifying high confidence peaks to remove them from background modelling
INFO - #######################################
INFO - Model background noise as a negative binomial
Optimization terminated successfully.
         Current function value: 4.083008
         Iterations: 5
         Function evaluations: 6
         Gradient evaluations: 6
INFO - Negative binomial overdispersion parameter: 0.566215325389091
INFO - #######################################
INFO - Identify effect of fragment size bias
INFO - #######################################
INFO - Estimating expected background levels from fragment size
INFO - #######################################
INFO - Identifying enriched regions using negative binomial model
INFO - #######################################
INFO - Refined peak calling done
INFO - #######################################
INFO - Writing peaks and bedgraph to output folder
Traceback (most recent call last):
  File "anaconda3-2021-05/install/envs/HiC-Pro_v3.1.0/bin/peak_call", line 8, in <module>
    sys.exit(main())
  File "anaconda3-2021-05/install/envs/HiC-Pro_v3.1.0/lib/python3.8/site-packages/hichip_peaks/main.py", line 130, in main
    smoothed_diagonal, refined_peaks ,quick_peaks, peak_p_vals , peaks_q_vals ,expected_background= sparse_to_peaks.sparse_to_peaks(CSR_mat,frag_index,frag_prop,frag_amount,valid_chroms,chroms_offsets,output_dir,prefix,off_diag,chromX,FDR=FDR,threads=threads,keeptemp=keeptemp)
  File "envs/HiC-Pro_v3.1.0/lib/python3.8/site-packages/hichip_peaks/sparse_to_peaks.py", line 74, in sparse_to_peaks
    bed_printout(frag_prop,smoothed_diagonal,refined_peaks,peak_p_vals,output_bed,output_bedgraph,expected_background,keeptemp)
  File "/anaconda3-2021-05/install/envs/HiC-Pro_v3.1.0/lib/python3.8/site-packages/hichip_peaks/sparse_to_peaks.py", line 348, in bed_printout
    output_file.write("{}\t{}\t{}\t{}\t{:10.15f}\n".format(frag_prop[i-1][0],math.floor((frag_prop[i-1][2]+frag_prop[i-1][1])/2),math.floor((frag_prop[i][2]+frag_prop[i][1])/2),max(smoothed_diagonal[i]-expected_background[i],0),-math.log10(peak_p_vals[i])))
ValueError: math domain error

**Comment by ChenfuShi** [comment]
Hi sorry for the late reply. 
Yes I think this could be happening, i've never seen this happen before. It seems that if the p_value goes to 0 then obviously you cannot calculate a log of the p_value. I guess you could try changing that line of code to test it if you are ok with it?
