### ISSUE TITLE
number of reads used for peak calling is very low. Consider doing more sequencing

### ISSUE THREAD

**Issue by gavinjzg** [ChenfuShi/HiChIP_peaks#21]
When I run the software, what should I do if this problem occurs?

**Comment by ChenfuShi** [comment]
Hi, it means that the software recorded less than 30 million reads for the peak calling. 
Can you check the number it gives you? 
if it's low (but not 0) it could be something to do with your libraries.

**Comment by gavinjzg** [comment]
NFO - Welcome to HiChIP-Peaks!
INFO - Version: 0.1.2
INFO - 2021-12-14 22:20:05.499570
INFO - Input variables
INFO - HiC-Pro data folder: /home/zjin/data/project/hic/500/hic_results/data/500 
INFO - Restriction fragment file: /home/zjin/data/project/hic/addition/homo.bed 
INFO - Chromosome annotation file: None 
INFO - Temporary location: /home/zjin/data/project/hic/results 
INFO - FDR: 0.01 
INFO - Distance from diagonal included: 2 
INFO - Output directory: /home/zjin/data/project/hic/results 
INFO - Output name prefix: 500 
INFO - Keep temporary files?: False 
INFO - Threads(minimum is 4): 4 
INFO - Sex chromosomes correction: False 
INFO - Store object containing sparse matrix: False 
INFO - Loading experiment information and read pairs
INFO - #######################################
INFO - Start reading experiment information (restriction fragments and chromosomes)
INFO - #######################################
INFO - Preparing HiC-Pro output for import
INFO - #######################################
INFO - Converting HiC-Pro to sparse matrix rappresentation of valid pairs at restriction site resolution
INFO - #######################################
INFO - Sparse matrix of experiment generated
INFO - Number of read pairs parsed: 0.0
INFO - #######################################
INFO - Extracting pairs for ChIP peaks calling
INFO - Number of reads used in peak calling: 0.0
WARNING - WARNING: number of reads used for peak calling is very low. Consider doing more sequencing
Traceback (most recent call last):
  File "/home/zjin/anaconda3/envs/hic-pro/bin/peak_call", line 8, in <module>
    sys.exit(main())
  File "/home/zjin/anaconda3/envs/hic-pro/lib/python3.7/site-packages/hichip_peaks/main.py", line 130, in main
    smoothed_diagonal, refined_peaks ,quick_peaks, peak_p_vals , peaks_q_vals ,expected_background= sparse_to_peaks.sparse_to_peaks(CSR_mat,frag_index,frag_prop,frag_amount,valid_chroms,chroms_offsets,output_dir,prefix,off_diag,chromX,FDR=FDR,threads=threads,keeptemp=keeptemp)
  File "/home/zjin/anaconda3/envs/hic-pro/lib/python3.7/site-packages/hichip_peaks/sparse_to_peaks.py", line 53, in sparse_to_peaks
    smoothed_diagonal = numpy.rint(moving_integration(diagonal,((off_diag-1)*2)+1)).astype(int) #### changed to 3 smoothing factor, it is one less than the number of off sites
  File "/home/zjin/anaconda3/envs/hic-pro/lib/python3.7/site-packages/hichip_peaks/sparse_to_peaks.py", line 86, in moving_integration

**Comment by gavinjzg** [comment]
it shows ValueError: v cannot be empty,what's the problem?

**Comment by ChenfuShi** [comment]
I think there is something wrong with the input. Are you using a recent version of HiCpro? can you check if the allvalidpairs file is correct? could you paste a few lines of that file?

**Comment by gavinjzg** [comment]
![)IQQ_ILDNOC${FB1)7)3$%O(1)](https://user-images.githubusercontent.com/52107940/146179540-49148070-fe8c-4058-b7af-8d257b7bdb5e.png) about 4.3g
  I have used 3.10. version and 2.1.1 version of hic，it also shows that

**Comment by ChenfuShi** [comment]
Ah I know what happened.
So basically the software expects the chromosomes to be chr1, chr2, etc whilst your data is formatted with chromosome 1,2 etc.
What you need to do is to supply the software with the annotation file 
  -a SIZES, --annotation SIZES
                        HiCpro chromosome annotation file, default uses human
                        chromosomes, excludes chrY
this is the file you use for running hic-pro, the one that contains the list of chromosomes with the size of each chromosome.
The software will take the name of the chromosomes from that file.
also i would exclude all the contigs and just have  in the file 1-22 + X

**Comment by gavinjzg** [comment]
When I add chr to the front of the chromosome,just like this
![mmexport1639646499333](https://user-images.githubusercontent.com/52107940/146343887-b732b16e-943d-423f-a003-b9f0e46efe31.png)

it still reports the error,what's the problem?

**Comment by gavinjzg** [comment]
![Uploading mmexport1639646507423.png…]()

**Comment by gavinjzg** [comment]
![mmexport1639646507423](https://user-images.githubusercontent.com/52107940/146344320-8a067670-55bb-4947-99a4-59ef1c854d6a.png)

**Comment by ChenfuShi** [comment]
have you given the right resfrag (-r) file in the command? the fragment names should match the ones in the validpairs file

**Comment by gavinjzg** [comment]
thanks sir，i get it！
